name: release
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: unit_test
        run: |
          go test -v ./lib/gcal_run/...

      - name: SetTag
        id: set_tag
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: build-package
        env:
          VERSION: ${{ env.tag }}
        run: |
          bash build.sh ${{ env.tag }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          VERSION: ${{ env.tag }}
        with:
          tag_name: ${{ env.tag }}
          release_name: Release ${{ env.tag }}
          draft: false
          prerelease: false

      - name: Upload Mac ARM64 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/gcal-run_darwin_arm64_${{ env.tag }}.tar.gz
          asset_name: gcal-run_darwin_arm64_${{ env.tag }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Mac AMD64 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/gcal-run_darwin_amd64_${{ env.tag }}.tar.gz
          asset_name: gcal-run_darwin_amd64_${{ env.tag }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/gcal-run_windows_amd64_${{ env.tag }}.zip
          asset_name: gcal-run_windows_amd64_${{ env.tag }}.zip
          asset_content_type: application/zip